apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-analytics
spec:
  selector:
    app: analytics-service
  ports:
    - port: {{ .Values.port }}
      targetPort: {{ .Values.port }}
  type: ClusterIP
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-analytics-config
data:
  KAFKA_BOOTSTRAP: {{ .Values.global.kafka.bootstrap | quote }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-analytics-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
